services:
  front:
    build: .
    tty: true
    volumes:
      - ../front:/front
    working_dir: /front
    command: sh -c "npm install && yarn start"
    ports:
      - 3001:3000
    networks:
      - mock
  back:
    build: .
    tty: true
    volumes:
      - ../back:/back
    working_dir: /back
    command: sh -c "npm install && npm run dev"
    ports:
      - 3002:3000
    networks:
      - mock

networks:
  mock:
    driver: bridge